Repository NullHooks/NullHooks, pull requests merged in 2022-06, with the labels that each got.

#11 Fix MH_Initialize typo
  src/core/hooks/hooks.cpp
Labels: typo

#12 Add findmdl hook for model changer
  src/core/features/features.hpp
  src/core/features/visuals/models.cpp
  src/core/hooks/functions/find_mdl.cpp
  src/core/hooks/hooks.cpp
  src/core/hooks/hooks.hpp
  src/csgo-cheat.vcxproj
  src/dependencies/interfaces/i_mdlcache.hpp
  src/dependencies/interfaces/interfaces.cpp
  src/dependencies/interfaces/interfaces.hpp
Labels: feature

#17 Update speedgraph in createmove
  src/core/features/features.hpp
  src/core/features/misc/speedgraph.cpp
  src/core/hooks/functions/create_move.cpp
  src/core/hooks/functions/paint_traverse.cpp
Labels: enhancement

#18 Disable model occlusion
  src/NullHooks.vcxproj
  src/core/hooks/functions/list_leaves_in_box.cpp
  src/core/hooks/hooks.cpp
  src/core/hooks/hooks.hpp
  src/dependencies/interfaces/iv_engine_client.hpp
  src/source-sdk/classes/entities.hpp
Labels: feature
