Repository NullHooks/NullHooks, pull requests merged in 2022-07, with the labels that each got.

#32 add bSendPacket to CreateMove
  src/core/hooks/functions/create_move.cpp
  src/core/hooks/hooks.cpp
  src/core/hooks/hooks.hpp
Labels: feature

#38 Skin changer and small config changes
  README.md
  config-examples/skins.json
  src/NullHooks.vcxproj
  src/core/config/config.cpp
  src/core/config/config.hpp
  src/core/features/features.hpp
  src/core/features/misc/commands.cpp
  src/core/features/visuals/skin_changer/read_skins.cpp
  src/core/features/visuals/skin_changer/skin_changer.cpp
  src/core/features/visuals/skin_changer/skin_changer.hpp
  src/core/hooks/functions/frame_stage_notify.cpp
  src/core/hooks/functions/viewmodel_sequence.cpp
  src/core/hooks/hooks.cpp
  src/core/hooks/hooks.hpp
  src/core/menu/menu.cpp
  src/core/menu/variables.hpp
  src/dependencies/rapidjson/allocators.h
  src/dependencies/rapidjson/cursorstreamwrapper.h
  src/dependencies/rapidjson/document.h
  src/dependencies/rapidjson/encodedstream.h
  src/dependencies/rapidjson/encodings.h
  src/dependencies/rapidjson/error/en.h
  src/dependencies/rapidjson/error/error.h
  src/dependencies/rapidjson/filereadstream.h
  src/dependencies/rapidjson/filewritestream.h
  src/dependencies/rapidjson/fwd.h
  src/dependencies/rapidjson/internal/biginteger.h
  src/dependencies/rapidjson/internal/clzll.h
  src/dependencies/rapidjson/internal/diyfp.h
  src/dependencies/rapidjson/internal/dtoa.h
  src/dependencies/rapidjson/internal/ieee754.h
  src/dependencies/rapidjson/internal/itoa.h
  src/dependencies/rapidjson/internal/meta.h
  src/dependencies/rapidjson/internal/pow10.h
  src/dependencies/rapidjson/internal/regex.h
  src/dependencies/rapidjson/internal/stack.h
  src/dependencies/rapidjson/internal/strfunc.h
  src/dependencies/rapidjson/internal/strtod.h
  src/dependencies/rapidjson/internal/swap.h
  src/dependencies/rapidjson/istreamwrapper.h
  src/dependencies/rapidjson/memorybuffer.h
  src/dependencies/rapidjson/memorystream.h
  src/dependencies/rapidjson/msinttypes/inttypes.h
  src/dependencies/rapidjson/msinttypes/stdint.h
  src/dependencies/rapidjson/ostreamwrapper.h
  src/dependencies/rapidjson/pointer.h
  src/dependencies/rapidjson/prettywriter.h
  src/dependencies/rapidjson/rapidjson.h
  src/dependencies/rapidjson/reader.h
  src/dependencies/rapidjson/schema.h
  src/dependencies/rapidjson/stream.h
  src/dependencies/rapidjson/stringbuffer.h
  src/dependencies/rapidjson/uri.h
  src/dependencies/rapidjson/writer.h
  src/dependencies/utilities/csgo.hpp
  src/source-sdk/classes/entities.hpp
Labels: good first issue, feature

#41 Edgebug pull request (Part 1, Engine Prediction)
  src/NullHooks.vcxproj
  src/core/features/aim/aimbot.cpp
  src/core/features/features.hpp
  src/core/features/misc/engine_prediction.cpp
  src/dependencies/interfaces/i_mdlcache.hpp
  src/dependencies/interfaces/i_player_movement.hpp
  src/dependencies/utilities/csgo.hpp
  src/dependencies/utilities/netvars/netvars.cpp
  src/dependencies/utilities/netvars/netvars.hpp
  src/source-sdk/classes/entities.hpp
  src/source-sdk/misc/datamap.hpp
Labels: feature-enhancement

#45 call GetIClientUnknown instead of using pointer arithmetic.
  src/core/hooks/functions/list_leaves_in_box.cpp
Labels: improvement

#48 Precached models and sv_pure bypass
  README.md
  src/NullHooks.vcxproj
  src/core/features/animations/local.cpp
  src/core/features/features.hpp
  src/core/features/misc/commands.cpp
  src/core/features/misc/thirdperson.cpp
  src/core/features/visuals/chams.cpp
  src/core/features/visuals/nosmoke.cpp
  src/core/features/visuals/player_esp.cpp
  src/core/features/visuals/skin_changer/read_skins.cpp
  src/core/features/visuals/skin_changer/skin_changer.cpp
  src/core/features/visuals/skin_changer/skin_changer.hpp
  src/core/helpers/globas.hpp
  src/core/helpers/helpers.cpp
  src/core/helpers/helpers.hpp
  src/core/hooks/functions/fire_event.cpp
  src/core/hooks/functions/frame_stage_notify.cpp
  src/core/hooks/functions/sv_pure.cpp
  src/core/hooks/hooks.cpp
  src/core/hooks/hooks.hpp
  src/core/menu/menu.cpp
  src/dependencies/interfaces/i_client_state.hpp
  src/dependencies/interfaces/i_client_string_table_container.hpp
  src/dependencies/interfaces/i_filesystem.hpp
  src/dependencies/interfaces/i_game_event_manager.hpp
  src/dependencies/interfaces/interfaces.cpp
  src/dependencies/interfaces/interfaces.hpp
  src/dependencies/interfaces/iv_model_info.hpp
  src/dependencies/utilities/csgo.hpp
  src/source-sdk/classes/entities.hpp
Labels: good first issue, feature

#51 Dynamic gui
  src/core/features/features.hpp
  src/core/menu/framework.cpp
  src/core/menu/framework.hpp
  src/core/menu/menu.cpp
  src/core/menu/variables.hpp
  src/dependencies/utilities/renderer/renderer.cpp
  src/dependencies/utilities/renderer/renderer.hpp
Labels: feature-enhancement

#59 Gradient bt chams, clean up code in hooks, quality of life improvments
  src/core/config/load.cpp
  src/core/config/save.cpp
  src/core/features/misc/spectator_list.cpp
  src/core/features/visuals/chams.cpp
  src/core/hooks/functions/sv_pure.cpp
  src/core/hooks/hooks.cpp
  src/core/hooks/hooks.hpp
  src/core/menu/menu.cpp
  src/core/menu/variables.hpp
  src/dependencies/utilities/csgo.hpp
  src/source-sdk/misc/color.hpp
Labels: improvement

#61 Add panorama, fix naming to proper casing, add last_command function to prediction
  src/NullHooks.vcxproj
  src/core/features/aim/aimbot.cpp
  src/core/features/misc/engine_prediction.cpp
  src/dependencies/interfaces/i_panoramaui_engine.hpp
  src/dependencies/interfaces/interfaces.cpp
  src/dependencies/interfaces/interfaces.hpp
  src/source-sdk/classes/entities.hpp
Labels: feature-enhancement
